[공예영] 1,2장: 21세기의 소프트웨어 개발, 애자일
muhandojeon/The-Software-Craftsman pull request #1
Opened 2024-10-02 07:23 UTC by yeyounging

2024-10-02 07:25 UTC, hyesungoh approved these changes
고생하셨어요 👍

2024-10-02 07:25 UTC, hyesungoh commented on 1장/공예영.md
> +- 쉽게 변경할 수 있는 소프트웨어
예영님은 테스트 및 배포 자동화 경험이 있으실까요??

2024-10-02 08:05 UTC, hyesungoh requested changes
1장 2장 파일을 분리해 주실 수 있으실까용?

2024-10-02 12:53 UTC, yeyounging commented on 1장/공예영.md
> +- 쉽게 변경할 수 있는 소프트웨어
저는 테스트 경험이 거의 없어서 오늘 모임 때 다른 분들의 경험을 여쭈어보았습니다 !! 저도 이번 프로젝트에 TDD 도입해보려구요 !

2024-10-02 20:40 UTC, hyesungoh approved these changes

2024-10-03 05:24 UTC, HoyeongJeon approved these changes

2024-10-03 05:24 UTC, HoyeongJeon commented on 1장/공예영.md
> +짧은 기간의 프로젝트를 수행하다보면 코드 품질은 버리다시피 하고 기능 구현에만 집중하는 것이 빈번했다. 이는 일회성 프로젝트에선 유효했지만, 지속적으로 유지보수를 해야하는 제품에서는 적절하지 못할 것이다. 앞으론 단순한 기능 구현보다 테스트 자동화, 가독성 좋은 코드 등 코드 품질에 집중해야겠다.
저도 프로젝트를 진행하면서 유지보수를 신경써본 적이 없어요.
대부분 프로젝트는 한번 모여서 끝내고 다신 안보니까요
그런데 최근 꾸준히 이어가고 운영해야 하는 프로젝트를 했는데, 유지보수를 신경쓰지 않으니 고생을 많이하게 되더라구요...
코드 품질의 중요성을 몸소 느끼게 되어 예영님의 글에 공감합니다.

2024-10-03 05:24 UTC, HoyeongJeon commented on 1장/공예영.md
> +짜여진 대로 코드만 짜는 것보다 능동적으로 사고하고 소통하는 것이 훨씬 흥미롭고 재밌다고 느낀다.
멋져요 👍👍
코드몽키가 되지 않기 위해 계속 노력해야겠네요

2024-10-03 05:24 UTC, HoyeongJeon commented on 2장/공예영.md
> +애자일 방법론을 도입한다고 해서 소프트웨어 제품의 품질이 대폭 향상되는 것은 아니다. 결국은 개발자들의 역량이 뛰어나야 높은 품질의 제품을 만들 수 있다.
저번 책도 그렇고 이번 책도 그렇고 항상 느끼는 점은 방법론 위에 사람이 있다는 점입니다. 
사람이 별로면 최고의 방법론과 도구를 가져다줘도 쓸모 없겠죠 ㅜ

2024-10-31 11:46 UTC, merged