[황동준] 4,5장: 영웅, 선의 그리고 프로페셔널리즘/ 동작하는 소프트웨어
muhandojeon/The-Software-Craftsman pull request #17
Opened 2024-10-31 11:35 UTC by nebulaBdj

2024-10-31 11:45 UTC, hyesungoh requested changes
1장이랑 2장 파일도 포함돼 있어요 ~

2024-10-31 12:17 UTC, hyesungoh requested changes
제목 수정과 1장 2장 파일 삭제 부탁드려요 ~

2024-11-02 03:57 UTC, hyesungoh approved these changes

2024-11-25 11:49 UTC, codrin2 approved these changes

2024-12-12 09:24 UTC, merged