[강연주] 5,6장: 영웅, 선의 그리고 프로페셔널리즘, 동작하는 소프트웨어
muhandojeon/The-Software-Craftsman pull request #18
Opened 2024-10-31 11:52 UTC by yeonjookang

2024-11-02 03:58 UTC, hyesungoh requested changes

2024-11-02 03:58 UTC, hyesungoh commented on .idea/misc.xml
여기 불필요한 파일들이 있어요 ~ 확인 부탁드려요

2024-11-14 07:26 UTC, yeonjookang commented on .idea/misc.xml
수정했습니다!

2024-11-14 07:29 UTC, hyesungoh approved these changes
👍 👍 👍

2024-11-25 11:49 UTC, codrin2 approved these changes

2024-12-12 09:25 UTC, merged