[전호영] 1,2장: 21세기의 소프트웨어 개발, 애자일
muhandojeon/The-Software-Craftsman pull request #2
Opened 2024-10-02 08:02 UTC by HoyeongJeon

2024-10-02 08:07 UTC, hyesungoh requested changes
고생하셨어요 👍 👍 👍 

1장과 2장 파일을 분리해 주실 수 있으실까용??

2024-10-02 12:57 UTC, yeyounging approved these changes

2024-10-02 12:57 UTC, yeyounging commented on 2장/전호영.md
> +-> 개발을 하면서 이제 다 완성이 됐다! 라는 순간에 다른 요구사항이 들어와 코드나 기능을 변경하게 될 때 즐거운 마음이었던 적은 없다. 하지만 이런 요구사항 변경을 환영하는 마음가짐을 가지고 개발을 해야겠다. 애자일 적인 마음가짐을 하나 배웠다 생각.
공감합니다.. 오히려 환영하는 마인드 !

2024-10-02 12:57 UTC, yeyounging commented on 2장/전호영.md
> +-> 이 문장을 보고 다시 정신을 차렸다. 나 역시도 '애자일'에 집중하고 있었다. 그러나 방법론도 시스템도 모두 개인의 성장, 조직의 성장을 위함을 잊고서 책을 읽었다. 배보다 배꼽에 더 집중했던 상황... 프로젝트를 진행할때도 애자일하게 해봐요! 라고 했지만 그게 우리 모두의 성장을 우선으로 한 얘기인지, 그냥 이번에 책을 읽어서 방법론만을 적용해봐야
개발자의 역량이 먼저라는 거 저도 와닿았습니다. 애자일이 프로젝트의 구원자일 거라는 생각이 은연중에 있었던 것 같아요

2024-10-03 05:19 UTC, HoyeongJeon commented on 2장/전호영.md
> +-> 개발을 하면서 이제 다 완성이 됐다! 라는 순간에 다른 요구사항이 들어와 코드나 기능을 변경하게 될 때 즐거운 마음이었던 적은 없다. 하지만 이런 요구사항 변경을 환영하는 마음가짐을 가지고 개발을 해야겠다. 애자일 적인 마음가짐을 하나 배웠다 생각.
'아 다 끝났는데...' 의 마음보단 '출시전에 더 좋은 서비스를 제공할 수 있는 기회를 얻어 다행이다!' 이런 쪽으로 생각해보려 합니다 ㅎㅎ

2024-10-03 05:20 UTC, HoyeongJeon commented on 2장/전호영.md
> +-> 이 문장을 보고 다시 정신을 차렸다. 나 역시도 '애자일'에 집중하고 있었다. 그러나 방법론도 시스템도 모두 개인의 성장, 조직의 성장을 위함을 잊고서 책을 읽었다. 배보다 배꼽에 더 집중했던 상황... 프로젝트를 진행할때도 애자일하게 해봐요! 라고 했지만 그게 우리 모두의 성장을 우선으로 한 얘기인지, 그냥 이번에 책을 읽어서 방법론만을 적용해봐야
공감합니다...!
애자일하게 가요! 말고 좀 더 구체적인 방법이나 예시 위주로 말하고 방법을 제시하기 전에 정말 팀과 나의 성장을 위한 것인지 생각하는 습관을 들여야겠어요

2024-10-03 13:18 UTC, hyesungoh approved these changes

2024-10-31 11:47 UTC, merged