[전호영] 11장,12장 : 잘못된 면접 방식, 낮은 사기의 대가
muhandojeon/The-Software-Craftsman pull request #37
Opened 2024-11-21 12:32 UTC by HoyeongJeon

2024-11-21 14:30 UTC, yeonjookang approved these changes

2024-11-21 14:30 UTC, yeonjookang commented on 11장/전호영.md
> +좋은 개발자를 찾기 어렵다란 얘기에 공감한다. 큐시즘엔 좋은 개발자가 많이 있다 느낀다. 서로 성장하고 싶어하는 사람들이 많이 모여있어 좋다. 책에서 좋은 동료를 찾기 위한 기준들이 나와있는데, 내가 그런 사람인지 되돌아보게 된다. 책 읽을때마다 되돌아보는 거 같다. 자아성찰 굳...
큐시즘 짱.... 👍

2024-11-21 14:30 UTC, yeonjookang commented on 12장/전호영.md
> +- 요즘 개발이 재밌다고 느끼는 이유 중 하나가 함께 하는 동료이다. 밋업을 함께하는 친구가 워낙 열심히 하고 기술적으로 성장하고 싶어하고 도와주려한다. 그런 모습과 호의를 보니 나도 더 열심히 해야곘단 마음이 들고 더 성장하고 싶다는 생각이 든다. 함께 하는 동료가 중요하다는 것을 느낀다.
동료가 열정적이면 같이 열심히하게 되는 것 같아요 😄

2024-11-22 03:25 UTC, hyesungoh approved these changes
호영님에게 좋은 감정과 생각들을 느끼게 해준 챕터같이 느껴져 보는 제가 기분이 좋네요 👍

2024-11-22 15:56 UTC, hyesungoh requested changes
정리하신 파일은 `README.md` 로 해주세요!!

2024-11-25 12:00 UTC, codrin2 approved these changes

2024-12-18 08:25 UTC, merged