[황동준] 1,2장: 21세기의 소프트웨어개발, 애자일
muhandojeon/The-Software-Craftsman pull request #8
Opened 2024-10-04 09:37 UTC by nebulaBdj

2024-10-05 14:19 UTC, hyesungoh approved these changes

2024-10-05 14:19 UTC, hyesungoh commented
2장 파일은 따로 올려주실 예정이실까요~? @nebulaBdj

2024-10-08 06:06 UTC, hyesungoh requested changes

2024-10-08 06:06 UTC, hyesungoh commented on 1장/황동준.md
> +팀과 조직이 어떻게 구성되고 협업해야 하는지에 대한 것들 규정
2장 내용은 파일을 분리 부탁드려요~

2024-10-08 07:43 UTC, nebulaBdj commented on 1장/황동준.md
> +팀과 조직이 어떻게 구성되고 협업해야 하는지에 대한 것들 규정
앗 알겠습니다

2024-10-08 08:26 UTC, hyesungoh approved these changes
👍 👍

2024-10-31 11:50 UTC, merged